# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 879a1fd85389e0933f52f5e8d30edb809c673697a24ed6457be9f677a395253b82193264d9fa4c55d0760fcf11dca698b1c1902ef1818e5159ec14f660cbd199

test:
  secret_key_base: 421db5491a230a796a30bc3d9f33ecb34ae7e1a44af778c314fbd6524e725da40bbaa35194f05819ebbca4ba610838f32ae1e90d9fbc2d332b3a7a701d021f1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
